---
kind: pipeline
name: "Push on master"

concurrency:
  limit: 2

steps:

  - name: "Verify & build"
    image: node
    commands:
      - npm install -g npm@8.5.3

  - name: "Build docker image"
    image: plugins/docker
    settings:
      repo: dshqq/week_6
      tags: ${DRONE_COMMIT_SHA:0:7}

