---
kind: pipeline
name: "Push on master"

concurrency:
  limit: 2

steps:

  - name: "Verify & build"
    image: node
    commands:
      - npm install
      - npm run build

  - name: "Build docker image"
    image: plugins/docker
    settings:
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      repo: dshqq/week_6
      tags: ${DRONE_COMMIT_SHA:0:7}

