---
kind: pipeline
name: "Push on master"

concurrency:
  limit: 2

steps:

  - name: "Verify & build"
    image: node
    commands:
      - npm install

  - name: "Build docker image"
    image: plugins/docker
    repo: dshqq/week_6
    tags: ${DRONE_COMMIT_SHA:0:7}



trigger:
  event:
    - push
