---
kind: pipeline
name: "Push on master"

concurrency:
  limit: 2

steps:

  - name: "Verify & build"
    image: node
    commands:
      - npm install
      - npm run build

  - name: "Build docker image"
    image: plugins/docker
    settings:
      registry_username:
        from_secret: username
      registry_password:
        from_secret: password
      repo: dshqq/week_6
      tags: ${DRONE_COMMIT_SHA:0:7}

