---
kind: pipeline
name: "Push on master"

concurrency:
  limit: 2

steps:

  - name: "Verify & build"
    image: node
    commands:
      - npm install
    when:
      branch:
        exclude:
          - main


trigger:
  event:
    - push
